### ISSUE TITLE
Change Linux password - doesn't work

### ISSUE THREAD

**Issue by wghay** [rescatux/rescapp#10]
Using Rescatux 0.40b11 on three separate systems (Lubuntu or LXLE), all old BIOS (non-UEFI). Tried 32-bit and 64-bit versions, and in all cases changing Linux password fails "Password not changed - something went wrong".
Rescatux 0.30.2 seems to work as expected.

**Comment by adrian15** [comment]
No recent feedback on the issue.
Closing the issue.
