### ISSUE TITLE
Reset GNU/Linux password does not work in old Lubuntu

### ISSUE THREAD

**Issue by adrian15** [rescatux/rescapp#16]
Version: Rescatux 0.40b6

The debug says something similar to: 'Cannot modify /etc/shadow file'.

I'll update the bug with specific Lubuntu version and specific error.

**Comment by RustyRaptor** [comment]
I'm currently getting this issue with ubuntu 16.04 installed alongside windows 10. 
http://paste.debian.net/1095638/ 

```
+ chpasswd -m --root /mnt/rescatux/sda5
chpasswd: failure while writing changes to /etc/shadow
```

**Comment by adrian15** [comment]
@RustyRaptor : Which Rescatux version were you using?

**Comment by RustyRaptor** [comment]
Wow the entry on debian paste is gone. I guess I should have copied it to pastebin. Unfortunately I don't remember what version it was. I downloaded and created the USB from the latest release about 2 weeks before I commented here if that helps. I no longer have the USB on me it is in the server room where I was working in the summer haha. If I ever go back to visit which I might I will check it out.

**Comment by adrian15** [comment]
@RustyRaptor :

- That was about one month ago. Rescatux 0.71-beta7 was out about threee months ago. So it might be it.

- I need confirmation though.

- I'm also interested in knowing if that Ubuntu 16.04 was a brand new installation or if it was upgraded from and old Ubuntu version. Having a passwd or shadow file inherited from an old Ubuntu distribution makes sense to me. It matches what you described originally.

- You can use the three  ` without spaces to quote those logs here so that they don't get lost.

**Comment by adrian15** [comment]
If someone else finds this bug please open a new issue.
Somehow I think this has been already fixed but I'm not 100% sure.

Closing the issue.
