### ISSUE TITLE
Rescapp not working on Fedora

### ISSUE THREAD

**Issue by MakuSensei** [rescatux/rescapp#3]

**Comment by adrian15** [comment]
Have you installed all the packages (or their Fedora packages equivalents) described in https://github.com/rescatux/rescapp/blob/9bd804ac687443b653953b15d856d4e76e185f2b/INSTALL#L81-L206 ?

**Comment by adrian15** [comment]
Supposing that you have installed Runtime requirements shown at: https://github.com/rescatux/rescapp/issues/3#issuecomment-340198885 Can you please run rescapp from the terminal / cli and report any error shown at the terminal?

Thank you.

**Comment by MakuSensei** [comment]
I do not have all the libraries that are installed

**Comment by adrian15** [comment]
> I do not have all the libraries that are installed

Do you mean that you do not have all the libraries that are needed?
Can you please install them then, please?

Or do you mean that you don't know which are the Fedora equivalents?
In such case you might ask help on Fedora forums or other support channels. Unless it's only two or three packages that you have doubts of.

I might help you with them then.
