### ISSUE TITLE
I want integrate rescapp in my own rescue linux distro and I cant do it

### ISSUE THREAD

**Issue by PinoitOS** [rescatux/rescapp#4]
Hi, my name is abraham, I am the creator of PinoitOS a Linux distro based in Debian 9.

The distro  consists in a rescue system, I have done scripts for make backup whatever you want, among other things, but, i am trying integrate rescapp and i cant do it...

I dont know if I am doing some fail, can someone could help me with information about the installation?

I tried installing the software like chntpw, rescapp from here(rescapp-master) and nothing is right...

I am 21 years old, and PinoitOS it's my final degree project, I would greatly appreciate the help

If  someone has managed to install it, if you do not mind, send me a email to abrahamsobrino96@gmail.com.

Thank you very much in advance,

A cordial greeting.

**Comment by adrian15** [comment]
El 05/04/18 a las 19:15, PinoitOS escribió:
> Hi, my name is abraham, I am the creator of PinoitOS a Linux distro
> based in Debian 9.
> 
> The distro consists in a rescue system, I have done scripts for make
> backup whatever you want, among other things
That's interesting. If you ever make it public please share a link
around here to see if I can recycle something from your work and add it
someday to Rescatux.

> but, i am trying integrate
> rescapp and i cant do it...
Nice. Feedback on improving rescapp documentation is welcomed.
> 
> I dont know if I am doing some fail, can someone could help me with
> information about the installation?

Maybe, the easiest way is to use the repo:

http://rescatux.sourceforge.net/repo/

which has instructions on how to use it.

> 
> I tried installing the software like chntpw, rescapp from
> here(rescapp-master) and nothing is right...

(Supposing you want something more than the prebuilt package binary
which it's available at the repo.)

Well,... if you want the equivalent of a Debian package you would have
to use the debian-dev branch instead of the master branch.

https://github.com/rescatux/rescapp/tree/debian-dev

And, in your case, you should be probably interested in: v0.52b3-debian tag.

https://github.com/rescatux/rescapp/tree/v0.52b3-debian

> 
> I am 21 years old, and PinoitOS it's my final degree project, I would
> greatly appreciate the help
> 
> If someone has managed to install it, if you do not mind, send me a
> email to
Github would probably send you a notification.
> 
> Thank you very much in advance,
Hopefully it helps you.
> 
> A cordial greeting.

**Comment by PinoitOS** [comment]
Hi @adrian15 thanks you so much for answer quite fast.

I will say you that I did, I am shure that I was do some fail.....


In first time I added this line in sources.list :

to serve of reference wrote

#Rescapp 
deb http://rescatux.sourceforge.net/repo/ jessie-dev main  

I was execute apt-get update, for refresh the repos, after this I executed make and make install, because I dont want a specifical installation.

And tried to lunch the app, typing rescapp, but it fails saying no module sip or something similar...

This project in very very important for me, if I have success I will get my degree.

Also I have thought, if would have a .deb package, because if there is, I prefer do dpkg -i [packagename.deb] and not extend the process of implementing the software.

 Thank you very much for answer.

**Comment by PinoitOS** [comment]
@adrian15 
Also say that in the moment that I executed apt-get install rescapp, I didnt find the package, right now, searching via web, I find that in the repo and I dont find the main directory I have only found 2 directory's, rescapp/ and chntpw/, I'm probably making a mistake but, there must have a folder call main?

Thanks

**Comment by adrian15** [comment]
El 06/04/18 a las 10:59, PinoitOS escribió:
> Hi @adrian15 <https://github.com/adrian15> thanks you so much for answer
> quite fast.
No problem.
> 
> I will say you that I did, I am shure that I was do some fail.....
Ok.

> 
> In first time I added this line in sources.list :
> 
> to serve of reference wrote
> 
> #Rescapp
> deb http://rescatux.sourceforge.net/repo/ jessie-dev main
It seems you haven't read the http://rescatux.sourceforge.net/repo/ page
as I recommended you.
It explains you have to use: stretch-dev for Debian 9.
Please advise how to improve its wording so that it's easier to understand.

> I was execute apt-get update, for refresh the repos,
Ok.
> after this I
> executed make and make install, because I dont want a specifical
> installation.
make and make install should only be used when trying to build the
package. Not when installing the binary package.

Not sure what do you mean when saying "I dont want a specifical
installation." Can you please reword your phrase?

> And tried to lunch the app, typing rescapp, but it fails saying no
> module sip or something similar...
It makes sense as it seems that you are installing a Debian 8 package in
a Debian 9 installation.
> This project in very very important for me, if I have success I will get
> my degree.
Good luck!

> Also I have thought, if would have a .deb package, because if there is,
> I prefer do dpkg -i [packagename.deb] and not extend the process of
> implementing the software.
Well, there is a .deb package in the repo which you can browse with an
internet browser, so that you can download it manually but it's actually
easier using the repo rather than not using it as you suggest.

> Thank you very much for answer.

Hopefully the stretch-dev solves the problem for you.
And, please, feedback is welcomed on rewording or reorganising the repo
inline documentation so that it's easier for people like you to
understand it.

**Comment by PinoitOS** [comment]
Hi @adrian15 

I'm sorry for not answering before, I've been literally trying to install rescapp all day, and I can't do it.

I have tried all the steps indicated in the repo, and I've been installing dependencies all day and I have not achieved anything, the last mistake I've had is associated with the depedence libntfs-3g852.

I've been looking for a lot of things about that dependency but I do not get to anything concrete.

I appreciate with all my soul the help you have given me, but if I can not install rescapp, I dont know if I'll be able to finish the project....

You have been able to install it in some distro?

If it's not too much to ask, could you give me a step-by-step tutorial?

I know I am a little annoyed, but I would appreciate your help, naming you in the project, as the main collaborator, I know it's not much, but it's all I can give you....

Thank you from the heart for all the help you have given me

Regards, I await your response.

**Comment by adrian15** [comment]
El 08/04/18 a las 01:45, PinoitOS escribió:
> Hi @adrian15 <https://github.com/adrian15>
> 
> I'm sorry for not answering before, I've been literally trying to
> install rescapp all day, and I can't do it.
Ok.
> 
> I have tried all the steps indicated in the repo,
Ok.
> and I've been
> installing dependencies all day
They are not needed. The apt-get command should take them into account.
> and I have not achieved anything, the
> last mistake I've had is associated with the depedence libntfs-3g852.
Aham.
> 
> I've been looking for a lot of things about that dependency but I do not
> get to anything concrete.
Interesting.
> 
> I appreciate with all my soul the help you have given me, but if I can
> not install rescapp, I dont know if I'll be able to finish the project....
I see.
> 
> You have been able to install it in some distro?
In all of the documented distros on the repo page.
> 
> If it's not too much to ask, could you give me a step-by-step tutorial?
No, I mean. Not yet. The repo instructions are indeed an step-by-step
turial.
> 
> I know I am a little annoyed, but I would appreciate your help, naming
> you in the project, as the main collaborator, I know it's not much, but
> it's all I can give you....
It's ok if you don't mention me.
> 
> Thank you from the heart for all the help you have given me
> 
> Regards, I await your response.

I suspect that my package for Debian 9 (Stretch) needs to be updated but
I'm not sure.

You already learnt how to interact with FOSS community by the means of
creating a github account and creating an account.

So, one thing you need to learn to fullfill your academic curriculum is
that within FOSS (Free and Open Source Software) communities you need to
be able to describe what you did.

Saying:

> I have tried all the steps indicated in the repo
> and I've been installing dependencies all day

is not helpful because we cannot track line by line what you exactly did.



Know you need to be able to copy and paste thanks to the three backticks
(`).

https://help.github.com/categories/writing-on-github/
https://help.github.com/articles/working-with-advanced-formatting/
https://help.github.com/articles/creating-and-highlighting-code-blocks

So, I ask you, two things please:

First write a comment on this issue about how you understand the
step-by-step tutorial in the repo page is to be understood.
Just copy and paste the instructions or commands (without the results)
in backsticks as the documentation (linked above) says.

Then, please, write another comment in this issue with your test. So
please write inside three backticks (`) both the commands you try and
also the output you are obtanining.

Thanks to those both comments I will be able to know:

* If the repo documentation is confusing
* If you are missing some steps
* If my package, somehow, needs to be updated.


Thank you very much and please do not give up !



adrian15
-- 
Support free software. Donate to Super Grub Disk. Apoya el software
libre. Dona a Super Grub Disk. http://www.supergrubdisk.org/donate/

**Comment by PinoitOS** [comment]
Hi @adrian15 
I'm going to tell you the steps I made:

1.- I removed all traces of rescapp of the system to do a clean installation with apt-get remove rescapp
2.- I added in the file source.list the line deb http://rescatux.sourceforge.net/repo/ stretch-dev main (in a system with i386 architecture)
3.- Yandex.Translate, [09.04.18 20:40]
I added in the file source.list the line deb http://rescatux.sourceforge.net/repo/ stretch-dev main (all-in-one system with i386 architecture)
4.- I ran apt-get update to refresh the repository
5.- I ran apt-get install rescapp, which gave me an error of dependencies

The dependencies that I have enclosed in the file named dependencies, 
[dependencias.txt](https://github.com/rescatux/rescapp/files/1891399/dependencias.txt)

it is worth mentioning that the following packages can be installed by hand, since the repo of debian do not have it : 

> rescapp_0.51b3-1_i386
> libssl1.0.0_1.0.1t-1+deb8u8_i386
> perl-base_5.20.2-3+deb8u9_i386
> libperl5.20_5.20.2-3+deb8u9_i386
> libgnutls-deb0-28_3.3.8-6+deb8u7_i386
> ntfs-3g-dev_2016.2.22AR.1+dfsg-1_i386
> libhogweed2_2.7.1-5+deb8u2_i386
> libnettle4_2.7.1-5+deb8u2_i386
> xchat_2.8.8-7.3_i386
> libsexy2_0.1.11-2.1_i386
> libapol4_3.3.8-3.1_i386
> libqpol1_3.3.8-3.1_i386
> python-setools_3.3.8-3.1_i386
> python-sepolicy_2.3-1_i386

Sorry if the content of the file dependencias.txt is in Spanish, my system is in Spanish language because I am from spain.

Once installed all the dependencies, emerged more dependencies, specifically the package xchat, the which you attached in another file called dependencias_xchat.txt
[dependencias_xchat.txt](https://github.com/rescatux/rescapp/files/1891408/dependencias_xchat.txt)

Once they are resolved the dependencies of xchat, in the beginning everything seemed to be fine, but began to appear dependencies of libraries redundant, which appeared of the package called python-pyqt5, are quite a few so that it will attached in a file called dependencias_python-pyqt5.txt
[dependencias_python-pyqt5.txt](https://github.com/rescatux/rescapp/files/1891410/dependencias_python-pyqt5.txt)

Once you have arrived at this point, the dependencies were changed, and the failure began to be generated around a library in a specific call libntfs-3g852, wich is associated to the application ntfs-3g, 

I have searched forums about that library, and as far as I have understood, the application itself installs, that's why I tried installing the-dev package.

At this point, it was 2 am and I decided to lie down for that he was very tired, but that was the last package that I was able to install as the failure of dependencies entered in a loop, saying "The package `libntfs-3g852' is not installed.

With regard to the tutorial that I told you in the previous comment, I have come to refer to a list of guided processes that is to say :

1.- "first install the package x"
2.- "once installed will give you the fault dependency called x, which is solved by installing the package x"

That kind of tutorial I was referring to.
I hope that the information I have provided has been of help to determine where is the fault.

Waiting for your response
Abraham Sobrino

**Comment by adrian15** [comment]
El 09/04/18 a las 21:40, PinoitOS escribió:
> Hi @adrian15 <https://github.com/adrian15>
> I'm going to tell you the steps I made:
> 
> 1.- I removed all traces of rescapp of the system to do a clean
> installation with apt-get remove rescapp
> 2.- I added in the file source.list the line deb
> http://rescatux.sourceforge.net/repo/ stretch-dev main (in a system with
> i386 architecture)
> 3.- Yandex.Translate, [09.04.18 20:40]
> I added in the file source.list the line deb
> http://rescatux.sourceforge.net/repo/ stretch-dev main (all-in-one
> system with i386 architecture)
> 4.- I ran apt-get update to refresh the repository
> 5.- I ran apt-get install rescapp, which gave me an error of dependencies
> 
> The dependencies that I have enclosed in the file named dependencies,
> dependencias.txt
> <https://github.com/rescatux/rescapp/files/1891399/dependencias.txt>
> 
> it is worth mentioning that the following packages can be installed by
> hand, since the repo of debian do not have it :
> 
>     rescapp_0.51b3-1_i386
>     libssl1.0.0_1.0.1t-1+deb8u8_i386
>     perl-base_5.20.2-3+deb8u9_i386
>     libperl5.20_5.20.2-3+deb8u9_i386
>     libgnutls-deb0-28_3.3.8-6+deb8u7_i386
>     ntfs-3g-dev_2016.2.22AR.1+dfsg-1_i386
>     libhogweed2_2.7.1-5+deb8u2_i386
>     libnettle4_2.7.1-5+deb8u2_i386
>     xchat_2.8.8-7.3_i386
>     libsexy2_0.1.11-2.1_i386
>     libapol4_3.3.8-3.1_i386
>     libqpol1_3.3.8-3.1_i386
>     python-setools_3.3.8-3.1_i386
>     python-sepolicy_2.3-1_i386
> 

I think I know what's happening in your system.

* Long and painful way:

Please make sure the:
jessie-dev line
either from:
```
/etc/apt/sources.list
```
or from:
```
/etc/apt/sources.list.d/rescatux.list
```
is removed.

Then you run:
```
apt-get update
apt-get remove rescapp chntpw
```
.


After this step you should clean up your system and remove (or replace
them with newer packages from stretch) all of those packages you decided
was a good idea to install manually (these are jessie packages and
should not usually be in an stretch system).

Once you have done if you have the stretch-dev line in place the
installation should work fine.

* Easy method:

If it's easier for you I recommend you to make a new Debian Stretch
installation and make sure use the stretch-dev line.
You will see how the rescapp installation is straight-forward.

* Feedback welcomed

Once again, if you manage to install rescapp I want some advice from you
on how to improve the repo documentation.

**Comment by adrian15** [comment]
El 09/04/18 a las 21:40, PinoitOS escribió:
> Hi @adrian15 <https://github.com/adrian15>
> With regard to the tutorial that I told you in the previous comment, I
> have come to refer to a list of guided processes that is to say :
> 
> 1.- "first install the package x"
> 2.- "once installed will give you the fault dependency called x, which
> is solved by installing the package x"
> 
> That kind of tutorial I was referring to.
> I hope that the information I have provided has been of help to
> determine where is the fault
Once you install a new Debian Stretch installation and read the repo
instructions as they are indented to be read you will realise the
tutorial as you describe it is not needed at all.

Why?

Because nobody will insist on installing Jessie packages on an Stretch
sytem.


Can you please run:

lsb_release -a

on your system and share with us its output?

Let's make sure you are actually using an Stretch system ;) .

Thank you.

**Comment by PinoitOS** [comment]
Hi @adrian15 

Sorry for taking a long time to respond, but a family member is in the hospital.

When your health improves, I perform the tests.

I'm sorry and sorry for the inconvenience.

Regards

**Comment by PinoitOS** [comment]
@adrian15 

This is the result that has offered me the command lsb_release -a

> root@PinoitOS:/home/wizard# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.4 (stretch)
Release:        9.4
Codename:       stretch

I hope that you help, 
Regards

**Comment by adrian15** [comment]
El 12/04/18 a las 17:10, PinoitOS escribió:
> @adrian15 <https://github.com/adrian15>
> 
> This is the result that has offered me the command lsb_release -a
> 
>     root@PinoitOS:/home/wizard# lsb_release -a
>     No LSB modules are available.
>     Distributor ID: Debian
>     Description: Debian GNU/Linux 9.4 (stretch)
>     Release: 9.4
>     Codename: stretch
> 
> I hope that you help,
> Regards

Ok, so you are in stretch.

Then you should use stretch-dev and remove any trace of jessie-dev on
your sources.list or sources.list.d/ files as I already suggested you.

**Comment by PinoitOS** [comment]
@adrian15 

I just remove all traces of jessie-dev and still giving me error of dependencies

I think I'm going to dismiss install this software, many thanks for all

**Comment by adrian15** [comment]
El 13/04/18 a las 13:10, PinoitOS escribió:
> @adrian15 <https://github.com/adrian15>
> 
> I just remove all traces of jessie-dev and still giving me error of
> dependencies
> 
> I think I'm going to dismiss install this software, many thanks for all

1) That's why I recommended you to start a new Stretch installation.
Dealing with package dependencies is not easy after you have forced to
install packages that weren't meant originally for the distro.

You would have to uninstall any forcefully installed package.

If you still refuse to start a new Stretch installation try to run:

apt-get install -f

which it will probably fail. Take note of the packages which have not
completed their installation.

And then apt-get remove any package that it's left uninstalled.

Try also to remove chntpw.

Finally try to run:

apt-get install -f

if nothing it's left to be done then try to install rescapp again.

2) If you are building a live OS... Why are testing to install rescapp
in an installed system ?

3) Is it so difficult for you to start a new Stretch installation in a
virtual machine and test the repo instructions as they are meant to be used?

**Comment by PinoitOS** [comment]
Hi @adrian15 

> 1) That's why I recommended you to start a new Stretch installation. Dealing with package dependencies is not easy after you have forced to install packages that weren't meant originally for the distro.
That is what I have done to perform all the tests to try to fix

> 2) If you are building a live OS... Why are testing to install rescapp in an installed system ?
On the basis of an already-installed system, once you have all the software and scripts that I consider necessary, I make an image live cd

> 3) Is it so difficult for you to start a new Stretch installation in a virtual machine and test the repo instructions as they are meant to be used?
There is nothing hard, that is what I have been doing up to now.

I don't know that else to do the truth, I think I've exhausted all the possibilities.

Regards.

**Comment by PinoitOS** [comment]
Hi @adrian15 

> 1) That's why I recommended you to start a new Stretch installation. Dealing with package dependencies is not easy after you have forced to install packages that weren't meant originally for the distro.

That is what I have done to perform all the tests to try to fix.

> 2) If you are building a live OS... Why are testing to install rescapp in an installed system ?

On the basis of an already-installed system, once you have all the software and scripts that I consider necessary, I make an image live cd

> 3) Is it so difficult for you to start a new Stretch installation in a virtual machine and test the repo instructions as they are meant to be used?

There is nothing hard, that is what I have been doing up to now.


I don't know that else to do the truth, I think I've exhausted all the possibilities.

Regards

**Comment by adrian15** [comment]
El 14/04/18 a las 14:07, PinoitOS escribió:
> Hi @adrian15 <https://github.com/adrian15>
> 
>      1. That's why I recommended you to start a new Stretch
>         installation. Dealing with package dependencies is not easy
>         after you have forced to install packages that weren't meant
>         originally for the distro.
> 
> That is what I have done to perform all the tests to try to fix.

Are you sure that you have installed a NEW Debian Stretch GNU/Linux
distribution installation in a new partition (or old one) or in a new
virtual machine AFTER having your dependencies problems ?

> 
>      2. If you are building a live OS... Why are testing to install
>         rescapp in an installed system ?
> 
> On the basis of an already-installed system, once you have all the
> software and scripts that I consider necessary, I make an image live cd

How are supposed to do so? What software are you going to use? Most of
the live cd making software don't asumme you to have an installed system
in order to generate a live cd.

> 
>      3. Is it so difficult for you to start a new Stretch installation
>         in a virtual machine and test the repo instructions as they are
>         meant to be used?
> 
> There is nothing hard, that is what I have been doing up to now.

Once again...

Are you sure that you have installed a NEW Debian Stretch GNU/Linux
distribution installation in a new partition (or old one) or in a new
virtual machine AFTER having your dependencies problems ?

> 
> I don't know that else to do the truth, I think I've exhausted all the
> possibilities.

If you are telling the truth (you have installed a Debian Stretch from
scratch, never used jessie-dev on it but used stretch-dev on it I'll
make a youtube stream in order to try to reproduce your problem.

adrian15
-- 
Support free software. Donate to Super Grub Disk. Apoya el software
libre. Dona a Super Grub Disk. http://www.supergrubdisk.org/donate/

**Comment by PinoitOS** [comment]
hi @adrian15 

> Are you sure that you have installed a NEW Debian Stretch GNU/Linux distribution installation in a new partition (or old one) or in a new virtual machine AFTER having your dependencies problems ?

Yes, it is a clean installation with the DVD of Debian.

> How are supposed to do so? What software are you going to use? Most of the live cd making software don't asumme you to have an installed system in order to generate a live cd.

I'm going to do an installation of the system, with the software that I think is needed, once they are made, the backup scripts, and installed software, with the program systemback generated a livecd of the distro.

> Are you sure that you have installed a NEW Debian Stretch GNU/Linux distribution installation in a new partition (or old one) or in a new virtual machine AFTER having your dependencies problems ?

Yes.

> If you are telling the truth (you have installed a Debian Stretch from scratch, never used jessie-dev on it but used stretch-dev on it I'll make a youtube stream in order to try to reproduce your problem.

ok, when you have made the stream, share the link to see if we have the same bug, anyway, I'm going to record a video performing a new installation. To see the steps that I do.

**Comment by adrian15** [comment]
>     If you are telling the truth (you have installed a Debian Stretch
>     from scratch, never used jessie-dev on it but used stretch-dev on it
>     I'll make a youtube stream in order to try to reproduce your problem.
> 
> ok, when you have made the stream, share the link to see if we have the
> same bug, anyway, I'm going to record a video performing a new
> installation. To see the steps that I do.

Here there is:

https://www.youtube.com/watch?v=Djj6qmHPKO4

**Comment by PinoitOS** [comment]
@adrian15 

> Here there is: https://www.youtube.com/watch?v=Djj6qmHPKO4



thanks you, this evening I will watch this.

Also I'd like to ask you, if we can speak in Spanish in other way, although we share the results here so that everyone can see the results.

I found the post of barrapunto in which I saw that you were or you were speaking Spanish, so I would prefer since that is my native language, and we could understand each other better.

Greetings and thanks for the link.

**Comment by adrian15** [comment]
2018-04-17 9:45 GMT+02:00 PinoitOS <notifications@github.com>:

> @adrian15 <https://github.com/adrian15>
>
> Here there is: https://www.youtube.com/watch?v=Djj6qmHPKO4
>
> thanks you, this evening I will watch this.
>
Ok.

> Also I'd like to ask you, if we can speak in Spanish in other way,
> although we share the results here so that everyone can see the results.
>
No, I'm sorry. I would prefer Spain to be a great country in the future and
the best way of achieving it is to make sure most Spain citizens learn to
speak an useful foreign language such as English.

> Greetings and thanks for the link.
>
Ok, hopefully you will be able to give me feedback on what you were not
understanding ok from the repo page.

**Comment by PinoitOS** [comment]
@adrian15 

Honestly, I thank life that there are people as wonderful as your.

Rescapp is installed in my distro, now you just have to finish off the details with some other application and scripts.

Following your steps it works, I don't know my dependencies errors have been using the dvd version or cd, I don't know but seriously, you've helped me a lot.

I'm going to appoint you as lead contributor.

When you have finished the distro, I'll share it with you to see how well it works your application on different distros.

A thousand thanks, you have a friend forever

**Comment by PinoitOS** [comment]
@adrian15 

here is the step by step tutorial for anyone who wants to install it, do so easily


1º sudo -i (to perform tasks as an administrator as being non-privileged user).
In the case of bash to show you the message -bash: sudo: not found the order
you just have to install the sudo command : apt-get install sudo

When you have it installed, as root open the file /etc/sudoers
and just below the line root ALL(ALL:ALL) ALL
you have to add : username ALL(ALL:ALL) ALL.

2ºadd this line in /etc/apt/sources.list.d/rescatux.list :
"deb http://rescatux.sourceforge.net/repo/ stretch-dev main"
in case you are working with debian 9.

3º apt-get update
4º apt-get install rescapp (when you install this package takes a long)
5º At the moment in the wizard of LILO appears, just press enter
 When you have installed and try to run the application, this does not start as it needs a graphical environment
6º we install the package task-lxde-desktop with apt-get install
probably not open and this is why we have to install xorg, and gdm3, with apt-get install (both packages)
7º We run service lightdm restart to choose the window manager (Select lightdm)

It will restart the window manager and the screen will be resized, will appear the login screen, once within the section of other, is the application of rescapp.

It may be the case that once inside the app, it may not work but is because you must have administrator permissions to work, the solution is run, gksudo rescapp and typ the pass of the user that run rescapp, and it will run correctly.

**Comment by adrian15** [comment]
> 
> Honestly, I thank life that there are people as wonderful as your.
You're welcome.
> 
> Rescapp is installed in my distro, now you just have to finish off the
> details with some other application and scripts.
Good luck with that.
> 
> Following your steps it works, I don't know my dependencies errors have
> been using the dvd version or cd, I don't know but seriously, you've
> helped me a lot.
I'm quite convinced you did not start a new Debian installation as you
stated.
> 
> I'm going to appoint you as lead contributor.
There's no need for that. Just make your distro greater.
> 
> When you have finished the distro, I'll share it with you to see how
> well it works your application on different distros.
Yeah, that's a nice feedback. Thank you !
> 
> A thousand thanks, you have a friend forever
I'll try to make you test newer Rescatux betas then ;) .

**Comment by adrian15** [comment]
> 
> here is the step by step tutorial for anyone who wants to install it, do
> so easily
> 
> 1º sudo -i (to perform tasks as an administrator as being non-privileged
> user).
> In the case of bash to show you the message -bash: sudo: not found the order
> you just have to install the sudo command : apt-get install sudo
> 
> When you have it installed, as root open the file /etc/sudoers
> and just below the line root ALL(ALL:ALL) ALL
> you have to add : username ALL(ALL:ALL) ALL.
Or you can just read Debian installation screens. If you leave blank the
root password then it creates a sudo user for you.
> 
> 2ºadd this line in /etc/apt/sources.list.d/rescatux.list :
> "deb http://rescatux.sourceforge.net/repo/ stretch-dev main"
> in case you are working with debian 9.
> 
> 3º apt-get update
> 4º apt-get install rescapp (when you install this package takes a long)
> 5º At the moment in the wizard of LILO appears, just press enter
> When you have installed and try to run the application, this does not
> start as it needs a graphical environment
> 6º we install the package task-lxde-desktop with apt-get install
> probably not open and this is why we have to install xorg, and gdm3,
> with apt-get install (both packages)
Well, I think you can just install lightdm and run: service lightdm
restart . No need of gdm3.
> 7º We run service lightdm restart to choose the window manager (Select
> lightdm)
> 
> It will restart the window manager and the screen will be resized, will
> appear the login screen, once within the section of other, is the
> application of rescapp.
> 
> It may be the case that once inside the app, it may not work but is
> because you must have administrator permissions to work, the solution is
> run, gksudo rescapp and typ the pass of the user that run rescapp, and
> it will run correctly.
Well, yes, most live cds work with a sudo (without a password) so... I
don't care about it too much.

**Comment by PinoitOS** [comment]
@adrian15 

> Well, yes, most live cds work with a sudo (without a password) so... I don't care about it too much.

That I was going to ask, I'm trying to make sure that the root user has no password, and I have not found a lot of information about you know about any manual or some forum in which to give any info?

**Comment by adrian15** [comment]
> 
>     Well, yes, most live cds work with a sudo (without a password) so...
>     I don't care about it too much.
> 
> That I was going to ask, I'm trying to make sure that the root user has
> no password, and I have not found a lot of information about you know
> about any manual or some forum in which to give any info?

This is not a rescapp question. Now you are on your own.
Good luck!

**Comment by PinoitOS** [comment]
ok, Im sorry...

Thanks!
