### ISSUE TITLE
Rescapp not saved in pendrive USB

### ISSUE THREAD

**Issue by Waldinrg** [rescatux/rescapp#49]
Every time I run Debian live nonfree  (debian-live-10.1.0-amd64-lxqt+nonfree.iso) on USB pendrive, I must run the line:
```
sudo apt update ; sudo apt install wget ; wget "http://rescatux.sf.net/repo/rescapp-nonfree-install.sh" -O rnfi.sh ; chmod +x rnfi.sh ; sudo ./rnfi.sh
```
To download and install Rescapp. It seems is installed on pendrive, but when I exit from debian live (next time I run again) Rescapp disappeared, I must download and install again.

It is normal? Thank you

**Comment by adrian15** [comment]
> Every time I run Debian live nonfree (debian-live-10.1.0-amd64-lxqt+nonfree.iso) on USB pendrive.

I'm curious. What is your special hardware? A graphics card?

What does happen when you try to boot Rescatux 0.72-beta1 in your machine?

**Comment by adrian15** [comment]
> To download and install Rescapp. It seems is installed on pendrive, but when I exit from debian live (next time I run again) Rescapp disappeared, I must download and install again.
> 
> It is normal? Thank you

Yes, it's normal. It is a live cd after all.

I have no idea if current Debian live cds support persistence but if you want it not to disappear you might want to take a look on using persistence on these pendrives.

**Comment by Waldinrg** [comment]
> Every time I run Debian live nonfree (debian-live-10.1.0-amd64-lxqt+nonfree.iso) on USB pendrive.
> 
> I'm curious. What is your special hardware? A graphics card?
> What does happen when you try to boot Rescatux 0.72-beta1 in your machine?

On all  my machines,  Rescatux 0.72-beta1 run Ok (less Gparted :-D), but I like try Rescatux non free Beta :-)

**Comment by Waldinrg** [comment]
> To download and install Rescapp. It seems is installed on pendrive, but when I exit from debian live (next time I run again) Rescapp disappeared, I must download and install again.
> It is normal? Thank you
> 
> Yes, it's normal. It is a live cd after all.
> I have no idea if current Debian live cds support persistence but if you want it not to disappear you might want to take a look on using persistence on these pendrives.

Ok. Thank you. I will see how do it :)

**Comment by adrian15** [comment]
> On all my machines, Rescatux 0.72-beta1 run Ok (less Gparted :-D), but I like try Rescatux non free Beta :-)

If you don't miss gparted too much you have a more complete system with the normal Rescatux iso.
