### ISSUE TITLE
 I need your authorization to use Rescapp in my Distro.

### ISSUE THREAD

**Issue by PinoitOS** [rescatux/rescapp#5]
Hi @adrian15 

I come back again, because I need your authorization to use rescapp in my distro, my professor's project, I have been asked your permission to use it.

I'm not going to earn money with it, only that you may be aware that I'm going to use it and give me your permission as the creator.

Many thanks in advance.

**Comment by adrian15** [comment]
El 07/05/18 a las 09:05, PinoitOS escribió:
> Hi @adrian15 <https://github.com/adrian15>
> 
> I come back again, because I need your authorization to use rescapp in
> my distro, my professor's project, I have been asked your permission to
> use it.
> 
> I'm not going to earn money with it, only that you may be aware that I'm
> going to use it and give me your permission as the creator.
> 
> Many thanks in advance.

Rescapp is licensed under the: GNU General Public License v3.0 .

You can find more information on what you can do and what you cannot do
with a GNU GPL v3 program on:

https://www.gnu.org/licenses/gpl-3.0.en.html
or maybe:
https://www.gnu.org/licenses/gpl-faq.es.html
or maybe:
https://www.gnu.org/licenses/gpl-faq.es.html#LinkingWithGPL

and many places on the Internet.


Please also take into account different scenarios:

* Use Rescapp as-is. (Need to include GNU GPL v3 and its source code
alongside it)

* Use Rescapp as a linked library inside another program with another
license (All your program should be licensed under GNU GPL v3). [I'm not
sure you it even makes sense to link any program to Rescapp as its
mainly a bash and python program but just in case be aware of it.]

* Use a modified version of Rescapp (The modified program must be GNU
GPL v3 too.)


I'm not a lawyer so take these pieces of advice as a grain of salt.
As I said there's plenty of information on the web.


The GNU GPL v3 has been always present at the COPYING file of the repo
so do not complain now about it.

Software licenses are very important and you should learn how to
distinguish between them, what you can do and not with them


Finally, as for my authorization you don't need an explicit
authorization from me.

As long as your usage of my program COMPLIES WITH GNU GPL v3 you are
free to use it without having to ask me anyhow.


adrian15
-- 
Support free software. Donate to Super Grub Disk. Apoya el software
libre. Dona a Super Grub Disk. http://www.supergrubdisk.org/donate/
