### ISSUE TITLE
Update Rescapp to work with sip 5.0.0

### ISSUE THREAD

**Issue by cjg67** [rescatux/rescapp#52]
Hello Adrian,

As per the chntpw thread, it seems that rescapp needs to be updated to work with the 5.x series of sip.

Regards,

Christopher.

**Comment by cjg67** [comment]
Hello Adrian,

In order for you to verify the error that occurs with `sip 5.0.0` you will need to use the fedora 30 rpms, as I have already updated the rpms for fedora 31. They will install on fedora 31.

https://sourceforge.net/projects/rescapp-fedora/files/Rescapp/Binary%20rpm/rescapp-0.54b2-1.fc30.x86_64.rpm

https://sourceforge.net/projects/rescapp-fedora/files/Rescapp/Source%20rpm/rescapp-0.54b2-1.fc30.src.rpm

Regards,

Christopher.

**Comment by adrian15** [comment]
I'm trying to focus on making Rescapp stable.
I'm not going to help you on testing Rescapp in an active manner for working in Fedora 31.

However I suspect the 'import sip' line is no longer any more after we no longer use the delete instrruction to recreate the layout.

Give it a go without the 'import sip' line and tell me if it breaks something or not.

If nothing seems to be broken I will add a commit that removes the 'import sip' line and I might release a new version for you to base your Fedora 31 package on.
