### ISSUE TITLE
Port Rescapp to Arch Linux

### ISSUE THREAD

**Issue by cjg67** [rescatux/rescapp#54]
Hello Adrian,

I have started to create a package to work on Arch Linux.

I have just done a manual install of rescapp on a standard installation of Arch, and have found that the following packages needed to be added on top of lxqt desktop, to get rescapp to actually run:

1. python-sip
2. python-pyqt5
3. qt5-webkit
4. xterm

The following optional packages are needed at runtime:

1. hexchat
2. inxi
3. gparted
4. testdisk

The only reason I added xterm above is that it is not installed as default and shows that it is not available when rescapp is first run.  The above are the package names in Arch.

I can tell you that to actually install Arch is kind of weird.  You do not get a nice fully graphical install like you do with Debian or Fedora.  Instead, you get a text console where you have been dropped into the installer shell, and you have to actually perform the installation stages in an arch-chroot.  There is an install.txt file there that has the procedures.  This is not what I would actually call a newbie friendly method of installation.

The unofficial graphical desktop that I mentioned in the thread that David started has an install to disk option on it, however it does not work.  It fails on creating the initrd image.

The other thing is, that Arch does not officially support SELinux, so I am not even going to attempt to list the packages as requirements to getting it to work, as I know nothing about SElinux, and there are a handful of packages that would need to be re-built to allow selinux support.  That is documented on ArchWiki.

The good news is, that Rescapp does actually run on Arch.

I am now going to go ahead and attempt the package creation.  It looks quite similar in some respects to the creating of packages for Fedora, ie it has its own package builder.

Once I get a package made, I will attempt to install it on my hard drive installed Arch, and then I will use the unofficial live dvd to test install it on.

With regards to inxi, it is a bit of a pig to get it to install, as the normal pacman -Sy inxi does not work, you have to install "yay" which is an AUR helper program, and then issue yay -S inxi.
Regards,

Christopher.

**Comment by adrian15** [comment]
> 1. python-sip

Did you ever try to run rescapp without the import python-sip line as I suggested you?

**Comment by cjg67** [comment]
Hello Adrian,

With everything I have been doing over the past few weeks to port my harddrives to using lvm I am going to need a refresher, where do I remove that line from?

I do not recall having done it, but I may have and forgotten.

Regards,

Christopher.

**Comment by adrian15** [comment]
> With everything I have been doing over the past few weeks to port my harddrives to using lvm I am going to need a refresher, where do I remove that line from?
> 
> I do not recall having done it, but I may have and forgotten.

After installing the package you just edit /usr/bin/rescapp and remove `import sip` line from it.

If you can open an option and go back to the main menu then I guess we can remove that line from upstream and thus that sip requirement.

**Comment by adrian15** [comment]
> Hello Adrian,
> 
> I have started to create a package to work on Arch Linux.

Nice.
 
> The following optional packages are needed at runtime:
> 
> 1. hexchat
> 2. inxi
> 3. gparted
> 4. testdisk

Please tell me how I can improve the current documentation found at: https://github.com/rescatux/rescapp/blob/master/INSTALL . Why? Gparted and testdisk are expert tools and thus they are optional. Hexchat and inxi are not optional.

> The only reason I added xterm above is that it is not installed as default and shows that it is not available when rescapp is first run. The above are the package names in Arch.

Yeah, rescapp needs xterm to be able to run some expert tools. Unless someone improves rescapp to support other graphical terminals as an xterm replacement. Not interesting in coding that part right now.

> I can tell you that to actually install Arch is kind of weird. You do not get a nice fully graphical install like you do with Debian or Fedora. Instead, you get a text console where you have been dropped into the installer shell, and you have to actually perform the installation stages in an arch-chroot.

I see. You do manually what an installer usually does.

> The unofficial graphical desktop that I mentioned in the thread that David started has an install to disk option on it, however it does not work. It fails on creating the initrd image.

Ok.

> The other thing is, that Arch does not officially support SELinux, so I am not even going to attempt to list the packages as requirements to getting it to work, as I know nothing about SElinux, and there are a handful of packages that would need to be re-built to allow selinux support. That is documented on ArchWiki.
> 
> The good news is, that Rescapp does actually run on Arch.

Using an Arch live cd where rescapp is installed in order to fix RedHat/Fedora/CentOS systems is not a good idea then. We should document that fact.

> I am now going to go ahead and attempt the package creation. It looks quite similar in some respects to the creating of packages for Fedora, ie it has its own package builder.
> 
> Once I get a package made, I will attempt to install it on my hard drive installed Arch, and then I will use the unofficial live dvd to test install it on.

Ok.

> With regards to inxi, it is a bit of a pig to get it to install, as the normal pacman -Sy inxi does not work, you have to install "yay" which is an AUR helper program, and then issue yay -S inxi.

No idea on how Arch packaging is done. You are in your own.

**Comment by cjg67** [comment]
Hello Adrian,

On my Arch linux install, I removed import sip and started rescapp and was able to open a number of the menu items and after I had let them run, I clicked on the menu button each time and everything worked.

Regards,

Christopher.

**Comment by cjg67** [comment]
Hello Adrian,

On Arch Linux (not sure about fedora or even rescatux at this stage) there seems to be an issue with check BIOS_GRUB PARTITION ON GPT.

After about five minutes it stops flashing that it is running,  and if you issue ps -auxf from a tty, you get the following:

`cjg        57048  0.1  2.0 2388244 155220 ?      Sl   18:07   0:02  |   \_ python3 /usr/bin/rescapp
cjg        57232  0.0  0.0      0     0 ?        Z    18:07   0:00  |   |   \_ [rescapp-launche] <defunct>
cjg        58995  0.1  1.9 2017472 151680 ?      Sl   18:30   0:01  |   \_ python3 /usr/bin/rescapp
cjg        59012  0.0  0.0      0     0 ?        Z    18:30   0:00  |   |   \_ [rescapp-launche] <defunct>
cjg        59038  0.0  0.0      0     0 ?        Z    18:31   0:00  |   |   \_ [rescapp-launche] <defunct>
cjg        59125  0.3  1.9 2016924 150516 ?      Sl   18:36   0:01  |   \_ python3 /usr/bin/rescapp
cjg        59140  0.0  0.0      0     0 ?        Z    18:37   0:00  |       \_ [rescapp-launche] <defunct>`

**Comment by adrian15** [comment]
> Hello Adrian,
> 
> On Arch Linux (not sure about fedora or even rescatux at this stage) there seems to be an issue with check BIOS_GRUB PARTITION ON GPT.
> 
> After about five minutes it stops flashing that it is running, and if you issue ps -auxf from a tty, you get the following:
> 
> In the display area, it appears to be just a white background, no error shows up there, and neither does any dialog. Only the Menu to select which disk is initially displayed.
> 
> This is with the tagged b4 version of rescapp.

When the disk selection dialog appear you are supposed to select that disk. You don't have to wait 5 minutes doing anything.

Anyways unless you are sure the option is safe I suggest you to test the different options 'run's in a live cd system inside a virtual machine.

**Comment by adrian15** [comment]
> In the display area, it appears to be just a white background, no error shows up there, and neither does any dialog. Only the Menu to select which disk is initially displayed.

Assuming you have installed python3-gi and python3-dbus packages this might be not having an accurate package dependencies description.

Rescapp needs dbus to run properly. That means that some system packages need to be installed (not sure what are the correct ones for Debian) so that there is a working dbus daemon. And then some cli packages are needed for the bash part.

Specifically for the rescapp bash scripts the _dbus-send_ command should be available. Once again I don't know what's the correct package for Debian.

**Comment by cjg67** [comment]
Hello Adrian,

The dbus-send is part of the dbus package, specifically it is located in the /tools sub-directory of the source code package.

The python3-gi I believe is the gobject introspection package for python 3.  Both that and a running dbus session are on Arch Linux.  I am currently using the gnome desktop and that heavily relies on dbus as well. In Debian, now that you ported to python 3 the package name is  python3-gi which is built from the source package pygobject (3.34.0-3).

I also need to make it clear that I waited 5 minutes *after* I clicked on the ok button in the select disk menu.  For some reason it is not working in Arch.  I will check in rescatux and fedora.

Regards,

Christopher.

**Comment by adrian15** [comment]
> I am currently using the gnome desktop and that heavily relies on dbus as well.

Rescapp installs an special dbus configuration file at: /etc/dbus-1/system.d/ named org.rescapp.MessageService.conf . Maybe Arch does not reload the dbus service/daemon after the package is installed. Have you tried reloading it manually after the package install?

**Comment by cjg67** [comment]
Hello Adrian,

I suspect it is something within Arch's packages that it does not like.  I tested it on rescatux beta 5 and it works flawlessly.

When I rebooted into Arch, this time when I clicked on the check bios_grub option, it did not even give me an option to select a disk.  It did however, say running for a couple of seconds, and then it said finished, and no dialog appeared on the screen area what so ever.

I will try it on a live cd.  Hopefully I can find an official live cd, rather than a community created one.

Regards,

Christopher.

**Comment by cjg67** [comment]
Hello Adrian,

Is there any way that you can create the release tar balls with the correct name, instead of v0.54b4.tar.gz?

Other people do it on github.  It would make it a lot cleaner for packaging as I notice that both Fedora and Arch like the package in the format of 

`$pkgname-$pkgver.tar.gz`

Its not a really big issue, as I can work around it, but it may make the package to be accepted by Arch and Fedora more readily.

Regards,

Christopher.

**Comment by cjg67** [comment]
Hello Adrian,

Well the good news is that it has been a rather painless task to create a package for Arch Linux.

The procedure produces a lot cleaner "build environment" than Fedora.  You do not have to go through the painful task of listing all files to be included in the package, and the package itself contains the files within their own subdirectories.  

I have not included a changelog as this is optional in Arch.

In following the Arch packaging guidelines you *may* not like nor agree with what they class things as.

For example hexchat, gparted, inixi and testdisk are, under Arch packaging guidelines classed as optional, as they are not required to install rescapp, but they are needed for added functionality.

The good news is, with Arch the optional dependencies have a description field, so I have listed the reason that they need to be included.

I now have to test the installation on the live dvd to make sure it will work.  I have to try and find out how to automatically pull in inxi as it is not in the main repositories as I stated above.  Sure "yay" is a way to install it, and does work, but I have come across a different package that may work better.

Worst case scenario is that I remove it from the depends altogether and put up a note how to install it manually.

This is what the PKGBUILD file looks like:

[PKGBUILD.txt](https://github.com/rescatux/rescapp/files/3935984/PKGBUILD.txt)

This is the package itself that I have to upload here so I can test it on the live dvd, it is also a tar.gz file so has to be extracted twice:

[rescapp.zip](https://github.com/rescatux/rescapp/files/3935985/rescapp.zip)

Regards,

Christopher.

**Comment by cjg67** [comment]
Hello Adrian,

Well it seems that the *real* challenge is to get a live dvd that actually has the correct base structure for installing rescapp on.  The so called lxqt version that I found and posted on Davids' thread will not run rescapp.  The package creation is sound, it just cannot find certain required files, which was not the case for Fedora.

So, I am now going to follow the arch-wiki and create my OWN live dvd.  This was not the way I had thought this would go.  It seems now, that this is going to be some sort of fork of rescatux in so much as it is going to be a live dvd with rescapp pre-installed.  

The reason for this is there is not enough space on the lxqt live dvd to actually install the missing qt5 base etc packages.  I have no idea *how* they even created the lxqt dvd without it.  That will remain a complete mystery to me.

Regards,

Christopher.

**Comment by cjg67** [comment]
Hello Adrian,

Well I have made my first ever live dvd.  I can confirm that the rescapp package that I created does indeed work when booted from the live dvd.

I have to do some debugging of the live dvd, namely I need to add the correct live user and get rescapp to actually be found.  I had to re-download and install.

I worked around the inxi problem by creating a local repository and adding both it and rescapp to it so that it would install on the created iso.  At the moment it complains when you try to update that the  custom repository was not found.

With the live image that I created, everything is up to date.  The tweaks should be minor, I will get it right.  But for a first ever attempt I am rather pleased with the results.  The main thing was testing rescapp.  Even the check bios_grub option works flawlessly.

I still have to create a package for samunlock, but will get the live dvd working correctly first.

Regards,

Christopher.

**Comment by cjg67** [comment]
Hello Adrian,

Well I have made a lot of progress on this.

I now have a live dvd that cleanly boots, I have managed to get it so that the liveuser account is created with a password, and is then added to the wheel group.  I have also, with the help of sed managed to enable the wheel group in the /etc/sudoers file.

Everything is working correctly with it.  It has inxi installed and running perfectly.

Now the nasty thing will not run rescapp that I installed at the creation of the live dvd.  It states in the creation that rescapp has been installed, but it is not to be found when I boot to the live dvd.

I downloaded the source code, and installed it, and it runs perfectly.

About the only thing left is for me to extract the .iso, mount it and enter arch-chroot and see if the package installs and runs from there.  The same package installs and works from my arch linux installed on the hard drive, so I can not understand it.

I hope your able to comment on this, and perhaps you have encountered this sort of issue before.

Please bear in mind, this is my first ever live dvd that I have created.

Regards,

Christopher.

**Comment by adrian15** [comment]
> Now the nasty thing will not run rescapp that I installed at the creation of the live dvd. It states in the creation that rescapp has been installed, but it is not to be found when I boot to the live dvd.
> 
> I downloaded the source code, and installed it, and it runs perfectly.
> 
> About the only thing left is for me to extract the .iso, mount it and enter arch-chroot and see if the package installs and runs from there. The same package installs and works from my arch linux installed on the hard drive, so I can not understand it.

Maybe you installed it on the binary part of the disk but not in the chroot one. The chroot one usually lives in a big-sized squashfs/unionfs/aufs file. The binary part of the disk would be whatever you see when you mount the iso-file as-is.

Hope it can give you a clue.

**Comment by cjg67** [comment]
Hello Adrian,

Well I did a trick that worked to a degree.  I followed arch wiki's guideline for remastering an iso.  I used arch-chroot and once I was inside the chroot, I downloaded the latest rescapp from your github account, and then I installed it from source.  I then re-assembled the iso, burnt it to dvd.

Once I booted I can confirm that there is now a fully functional version of rescapp installed.

As Arch linux do not actually have an "official" graphical live dvd, I think that this will be sufficient.

I know that the package I created can be installed and function on an installed to hard drive Arch linux.

I just need to re-do the live dvd with samunlock.

I have absolutely no idea why the package that gets installed with pacman will not actually get installed.  Inxi gets installed exactly the same way, ie from a custom repository at the build stage of the live dvd, and that works perfectly.

Please let me know if you are willing to give this a test run, as I will need to upload this to sourceforge, as it is 2.2gig.  I think I should do the samunlock first.

I can, attempt a version of this same dvd using only the freedom drivers.  It will mean removing the linux-firmware that gets installed.  That way we could make you an "official" version of rescatux based on arch.  Or we could just leave it as unofficial.

Regards,

Christopher.

**Comment by cjg67** [comment]
Hello Adrian,

I was not able to leave it alone.  I spent a number of hours trying to build the live dvd a different way and it kept failing, due to omitted documentation.

I found by shear accident, during the many failed attempts, that it finally added both rescapp and inxi to the list of installed packages.  The only change that I made was to add the custom repository to the  system version of pacman.conf and to re-initialize the keys on the system.  That still did not produce any iso.

Out of shear frustration I went back to the other method of creating the dvd that worked, and this time after I had burnt the dvd, and rebooted.  I have a fully working rescapp installed.

No where on Arch Wiki, or on the numerous websites that I visited did it state that you had to also add the custom repository to the system version of pacman.conf.  They all state to add it in the build directory.

This working version of rescapp is a version that is packaged for Arch Linux.

I am now going to go ahead and create the package to get samunlock working, and then I will upload the live dvd to sourceforge, and hopefully you will have time to test it.

Regards,

Christopher.

**Comment by cjg67** [comment]
Hello Adrian,

Well I have added the chntpw package that I made for Arch Linux to the live dvd.  I can confirm that the live dvd boots cleanly and rescapp does detect samunlock.

The unfortunate thing is, that you have to manually install chntpw, as it installed the version off Arch's server over mine.  That can be easily fixed in another version of the dvd.  For now, I would appreciate it if you could test resapp.

You can download the live dvd from:

https://sourceforge.net/projects/rescapp-arch-linux/files/rescapp-livedvd/archlinux-2019.12.14-x86_64.iso

This dvd is 2.0 gigs.

The username is liveuser and the password is live.

To install my version of chntpw you can open a terminal and the package should be there.  If it is not then /home/liveuser/Downloads will definately have it.

To install the package:

`sudo pacman -U chntpw-1.01-1-x86_64.pkg.tar.xz`

In order to get to both rescapp and the other programs there is a launcher on the bottom left of the screen, a small blue white globe.

Regards,

Christopher.

**Comment by cjg67** [comment]
Hello Adrian,

I was thinking, that even though Arch Linux does not officially support SELinux, if you have a deep knowledge of its working, I could re-compile the list of packages that need to have it added for it to be recognized.  

I have no idea how to write the policies for it, but if you do, then perhaps we could get it to work on a live dvd, so that it could be used by experts for Arch and other distros that use SELinux.

Now that I know the build procedure for the Arch live dvd I can add and remove whatever packages from the build script file list.

Regards,

Christopher.

**Comment by adrian15** [comment]
> Hello Adrian,
> 
> I was thinking, that even though Arch Linux does not officially support SELinux, if you have a deep knowledge of its working, I could re-compile the list of packages that need to have it added for it to be recognized.
> 
> I have no idea how to write the policies for it, but if you do, then perhaps we could get it to work on a live dvd, so that it could be used by experts for Arch and other distros that use SELinux.
> 
> Now that I know the build procedure for the Arch live dvd I can add and remove whatever packages from the build script file list.
> 
> Regards,
> 
> Christopher.

I told you to test a live cd inside a virtual machine so that you did not break your own installed system by accident while trying the different rescapp options.

There's no need to improve you current rescapp Arch-based live cd till it's production ready.

I will test your uploaded iso and give you feedback later.

**Comment by adrian15** [comment]
> Hello Adrian,
> 
> Well I have added the chntpw package that I made for Arch Linux to the live dvd. I can confirm that the live dvd boots cleanly and rescapp does detect samunlock.
> 
> The unfortunate thing is, that you have to manually install chntpw, as it installed the version off Arch's server over mine. That can be easily fixed in another version of the dvd. For now, I would appreciate it if you could test resapp.
> 
> You can download the live dvd from:
> 
> https://sourceforge.net/projects/rescapp-arch-linux/files/rescapp-livedvd/archlinux-2019.12.14-x86_64.iso
> 
> This dvd is 2.0 gigs.
> 
> The username is liveuser and the password is live.
> 
> To install my version of chntpw you can open a terminal and the package should be there. If it is not then /home/liveuser/Downloads will definately have it.
> 
> To install the package:
> 
> `sudo pacman -U chntpw-1.01-1-x86_64.pkg.tar.xz`
> 
> In order to get to both rescapp and the other programs there is a launcher on the bottom left of the screen, a small blue white globe.
> 
> Regards,
> 
> Christopher.

I have done a quick test on your iso and it seems to work quite well. After installing chntpw samulock --help works and trying Easy GNU/Linux boot fix and fsck options do work also.

**Comment by cjg67** [comment]
Hello Adrian,

Well I did some reading on Arch Wiki, and they recommend building packages in a clean chroot environment.  I have now set this up, so all future PKGBUILD of packages will be done this way.  It ensures that I do not accidently miss putting any required files in the appropriate sections and that a clean version of pacman.conf is uesd at every build, rather than what is installed on the current system.

I will also check if the same is offered with Fedora.  I want the packages that I create to work out of the box, without any surprises for end users.

I am also glad that your initial quick test was successful.

Regards,

Christopher.

**Comment by cjg67** [comment]
Hello Adrian,

Well you have got to love sourceforge.  I have added no help page, no about page, just that iso so that you could test it, and already 12 people other than you have downloaded it.

Regards,

Christopher.

**Comment by cjg67** [comment]
Hello Adrian,

I have added a wiki page to the port to Arch Linux, explaining the differences between your version and the original.  I have sited the original authors' website along with yours and the changes that you have made.

You can view it here:

https://sourceforge.net/p/rescapp-arch-linux/wiki/Home/

Regards,

Christopher.

**Comment by cjg67** [comment]
Hello Adrian,

Well I have done some more work on the Wiki page.  I think that I have now covered everything that needs to be covered.  I will now leave it as it is, and allow you, time permitting, to read it and make any suggestions that you think would improve it.

Regards,

Christopher.

**Comment by adrian15** [comment]
> Hello Adrian,
> 
> Well I have done some more work on the Wiki page. I think that I have now covered everything that needs to be covered. I will now leave it as it is, and allow you, time permitting, to read it and make any suggestions that you think would improve it.
> 
> Regards,
> 
> Christopher.

You might want to add a Webpage link option under the Sourceforge project which links to the wiki page.

 - Please link to: https://www.supergrubdisk.org/rescatux/ instead of linking to the beta downloads page.
 - Typo: devleloped
 - Typo: 740 x 680 . Did you mean 640x480 or 800x600 instead ?

**Comment by dimyme** [comment]
> After installing the package you just edit /usr/bin/rescapp and remove `import sip` line from it.
 

`/run/archiso/sfs/airootfs/usr/bin/rescapp`

may or may **not** work or be or **not** be there. people whose machine just crashed usually like very much to look for files, because, heck, menus are for losers and people afraid to write a PhD thesis with EDLIN.EXE in MSDOS 1.0

**Comment by adrian15** [comment]
> > After installing the package you just edit **/usr/bin/rescapp** and remove `import sip` line from it.
> 
> `/run/archiso/sfs/airootfs/usr/bin/rescapp`
> 
> may or may **not** work or be or **not** be there. people whose machine just crashed usually like very much to look for files, because, heck, menus are for losers and people afraid to write a PhD thesis with EDLIN.EXE in MSDOS 1.0

These line is not found on the latest rescapp version.
@cjg67 arch live cd does not contain the latest rescapp version. That's why you encountered this problem.

Porting rescapp to arch is not an straight-forward task.

Maybe if you have arch packaging skills you can help @cjg67 to update his code to the current version.

**Comment by adrian15** [comment]
No recent feedback on this issue.
Closing the issue.
