### ISSUE TITLE
Documentation fix ups

### ISSUE THREAD

**Issue by cjg67** [rescatux/rescapp#55]
Hello Adrian,

I am now in the process of going through your code and checking all the documentation that I can find for errors.  I will post them all in this thread, so that we do not have many open issues.

Inxi can be setup to show more or less information of your system. Here we will describe Rescapp 
tuning of inxi so that you know what you are going to share with other people which might want to help you.

Change to:

Inxi can be setup to show more or less information about your system.  Here we will describe the Rescapp tuning of inix so 
that you know what you are going to be sharing with other people who might want to assist you.

Informs the user that the log is finished and the several ways it has to share it.

Change to:

Informs the user that the log file is finished, and the ways that it can be shared.

INXI_EXPLANATION="Check the Support menu in order to see how you can show, share, share on forums, etc. the Inxi log."

Change to:

INXI_EXPLANATION="Check the Support menu in order to see how you can display or share on the forums the Inxi log."

`detailsWarning = "Samunlock binary was not found.\nYou might be missing Rescatux chntpw package.\nYou won't be able to unlock users in Windows options."
            self.report(self.ResultType.Warning, "samunlock NOT found.", detailsWarning)`

Change to:

`       detailsWarning = "Samunlock binary was not found.\nYou need to install the Rescatux chntpw package.\nYou will not be able to unlock users in Windows options without it."
            self.report(self.ResultType.Warning, "samunlock NOT found.", detailsWarning)`

`        detailsWarningCommon = "You might be missing SELinux support.\nTrying to rescue Fedora/RHEL/CentOS systems will probably end on you having to recreate SELinux permissions manually thanks to a .autorelabel file which might take hours. It's probably better to use another live cd that supports SELinux such as Rescatux."`

Change to:

`        detailsWarningCommon = "You are missing SELinux support.\nTrying to rescue Fedora/RHEL/CentOS systems will probably end up with you having to recreate SELinux permissions manually, thanks to a .autorelabel file which may take hours. It is probably better to use another live cd that supports SELinux such as Rescatux."`

`            detailsSkip = "Rescapp has been boot in UEFI mode. If you are trying to fix boot on a BIOS booted installed system please make sure your media boots in BIOS mode instead of UEFI mode."
            self.report(self.ResultType.Skip, "Booted in UEFI (non BIOS) mode.", detailsSkip)`

Change to:

`           detailsSkip = "Rescapp has been booted in UEFI mode. If you are trying to fix booting on a BIOS booted installed system please make sure your media boots in BIOS mode instead of UEFI mode."
            self.report(self.ResultType.Skip, "Booted in UEFI (non BIOS) mode.", detailsSkip)`

With the following, you need to provide examples of which external programs will not open within rescapp, and add an "s" to the end of program:

`detailsWarning = "Xterm binary was not found.\nYou won't be able to open some external program from within Rescapp." self.report(self.ResultType.Warning, "xterm NOT found.", detailsWarning)`

This now also needs to be removed:

`import sip`

`BOOT_INFO_SCRIPT_EXPLANATION="Check the Support menu in order to see how you can show, share, share on forums, etc. the Boot Info Script log."`

Change to:

`BOOT_INFO_SCRIPT_EXPLANATION="Check the Support menu in order to see how you can display or share on the forums the Boot Info Script log."`

`XCHAT_OK_STR="Hexchat was run at the background."`

Change to:

`XCHAT_OK_STR="Hexchat was run in the background."`

`Step 2

If such partitions have been found Rescapp presents you partitions that have on them the following file: /etc/issue. At the same time you are prompted:

Which partition is your main GNU/Linux?

You are supposed to choose your main GNU/Linux distribution (probably you only will see one) and press the OK button.`

Change to:

```
`Step 2

If such partitions have been found, Rescapp displays the partitions that have on them the following file: /etc/issue. At the same time you are prompted:


Which partition is your main GNU/Linux?

You are supposed to choose your main GNU/Linux distribution (probably you will only see one) then press the OK button.`

```

```
 <b>Step 2</b><p></p>Rescapp presents you found partitions on Step 1.<p></p>You are prompted:<p></p>
  <i>Which partition?</i><p></p> You are supposed to choose whatever partition you want to force filesystem check and press the OK button.<p></p>Explanation of description is:
    <ul>
```

Change to:

```
 <b>Step 2</b><p></p>Rescapp presents you with the partitions found on Step 1.<p></p>You are prompted:<p></p>
  <i>Which partition?</i><p></p> You are supposed to choose whatever partition you want to force the filesystem check on, and press the OK button.<p></p>Explanation of description is:
    <ul>
```

```
	<b>Not detected</b>: The partition can be mounted but there is not a <i>/etc/issue</i> fie on it. Probably a non root partition.
      </li>
```

Change to:

```
	<b>Not detected</b>: The partition can be mounted but there is not a <i>/etc/issue</i> file on it. It is probably a non root partition.
      </li>
```

```
	<b>Can't mount:</b>: The partition cannot be mount. Maybe it is the partition you want to fix, another one that Rescatux cannot mount, or probably a SWAP partition.
      </li>
```

Change to:

```
	<b>Can't mount:</b>: The partition cannot be mounted. Maybe it is the partition you want to fix, one that Rescatux cannot mount, or maybe a SWAP partition.
      </li>
```

```
  <b>Step 4</b><p></p>You are informed about the fsck process.<p></p>Message is self explanatory. You either get:<p></p><i>Success! Filesystem check with automatic fix was OK! :)</i><p></p>or<p></p><i>Filesystem check with automatic fix went wrong! :(</i>
  </li>

```
Change to:

```
  <b>Step 4</b><p></p>You are informed about the fsck process.<p></p>You either get:<p></p><i>Success! Filesystem check with automatic fix was OK! :)</i><p></p>or<p></p><i>Filesystem check with automatic fix went wrong! :(</i>
  </li>
```

```
  <b>Step 6</b><p></p>A log file called <i>fsck.log.txt</i> can be found at Desktop <i>logs</i> folder.
  </li>

```
Change to:

```
  <b>Step 6</b><p></p>A log file called <i>fsck.log.txt</i> can be found in the Desktop <i>logs</i> folder.
  </li>
```

`FSCK_PARTITIONS_NOT_FOUND="No partitions were found or choosen."`

Change to:

`FSCK_PARTITIONS_NOT_FOUND="No partitions were found or selected."
`

`GPARTED_OK_STR="Gparted was run at the background."
`

Change to:

`GPARTED_OK_STR="Gparted was run in the background."
`

`GPARTED_KO_STR="Rescapp was not unable to start Gparted."
`

Change to:

`GPARTED_KO_STR="Rescapp was not able to start Gparted."
`

```
Do you actually need a bios_grub partition ? Probably not but it depends. A bios_grub partition is usually needed if you use grub-pc on a GPT disk. 
If your computer has both a GPT disk and EFI boot support you might be better on trying to install grub-efi package. 
If you need to use grub-pc package on a GPT disk after all this option let's you find if your targeted hard disk has the bios_grub partition or not. 
If you think that you need to create a bios_grub partition please ask to your distribution usual support places. 
An option to help you to create a bios_grub partition is not on the short term Rescatux TODO list.
<br/>

```

Change to:

```
Do you actually need a bios_grub partition? Probably not but it depends. A bios_grub partition is usually needed if you use grub-pc on a GPT disk. 
If your computer has both GPT disk and EFI boot support you might be better off trying to install the grub-efi package. 
If you need to use grub-pc package on a GPT disk after all, this option let's you find if your targeted hard disk has the bios_grub partition or not. 
If you think that you need to create a bios_grub partition please ask on your distributions usual support places. 
An option to help you create a bios_grub partition is not on the short term Rescatux TODO list.
<br/>

```
```
  <b>Step 2</b><p></p>If such hard disks have been found Rescapp presents you the hard disks. At the same time you are prompted:<p></p>
  <i>Which hard disk?</i><p></p> You are supposed to choose the hard disk which has a GPT partition which you want its bios_grub partition to be checked.
  </li>



```
Change to:

```
<b>Step 2</b><p></p>If such hard drives have been found Rescapp shows you the list of hard drives. At the same time you are prompted:<p></p>
  <i>Which hard drive?</i><p></p> You are supposed to choose the hard drive which has a GPT partition on which you want its bios_grub partition checked.
  </li>
```

```
  <b>Step 3</b><p></p>Rescapp with all gathered information is going to check if there is a bios_grub partition inside your GPT hard disk.<b>Please wait</b>. 
Currently (Rescatux 0.40b1) this step is time consuming but no Please wait message has been implemented.
  </li>
```

Change to:

```
  <b>Step 3</b><p></p>Rescapp with all the gathered information is now going to check if there is a bios_grub partition inside your GPT hard drive.<b>Please wait</b>. Currently, with (Rescatux 0.40b1) this step is time consuming, but no Please wait message has yet been implemented.
  </li>
```

```
 <b>Step 4</b><p></p>You are informed about the bios_grub checking process.<p></p>Message is self explanatory. You either get:<p></p><i>bios_grub partition was found! :)</i><p></p>or<p></p><i>bios_grub partition was not found. :(</i>
  </li>

```
Change to:

```
 <b>Step 4</b><p></p>You are informed about the bios_grub checking process.<p></p>You either get:<p></p><i>bios_grub partition was found! :)</i><p></p>or<p></p><i>bios_grub partition was not found. :(</i>
  </li>
```
```
 <b>Step 5</b><p></p>A log file called <i>gpt-check-bios-grub_log.txt</i> can be found at Desktop <i>logs</i> folder.
  </li>
```

Change to:

```
 <b>Step 5</b><p></p>A log file called <i>gpt-check-bios-grub_log.txt</i> can be found in the Desktop <i>logs</i> folder.
  </li>
```

`WHICH_HARD_DISK_BIOS_GRUB_PARTITION_STR="Which hard disk to check if it has a bios_grub partition?"
`

Change to:

`WHICH_HARD_DISK_BIOS_GRUB_PARTITION_STR="Which hard drive to check for a bios_grub partition on?"
`

`BIOS_GRUB_HARD_DISK_NOT_FOUND="No disks were found or choosen."
`
Change to:

`BIOS_GRUB_HARD_DISK_NOT_FOUND="No drives were found or selected."`

Regards,

Christopher.

**Comment by cjg67** [comment]
Hello Adrian,

I am only part way through checking the documentation in the plugins folder.  I am up to gpt-create-hybrid-mbr, but I am now going to take a break for now.

I will let you know when I have completed everything.

Regards,

Christopher.

**Comment by adrian15** [comment]
Can you please create a new branch out of the https://github.com/rescatux/rescapp/tree/trap branch and make commits there so that you can later on ask for a pull request?

Thank you.

**Comment by cjg67** [comment]
Hello Adrian,

I never thought of that!!  It will make things so much easier.  I will create that on my account, and then make all the changes there and then, after you have checked everything you can make the changes to your main code base.  That way I do not need to copy and paste here.

Sorry for not thinking of that myself.  You have asked me a few times if there are improvements, and I was doing other things as well, and this kind of got pushed into the background. It is a long process, but once complete it means that you will be closer to being able to make a "stable" release of rescatux/rescapp.

Regards,

Christopher.

**Comment by cjg67** [comment]
Hello Adrian,

Well I am sorry but I need assistance with getting things to actually appear on github.  I am going around in circles.

What I have achieved with git is:

git remote -v
origin	https://github.com/cjg67/rescapp.git (fetch)
origin	https://github.com/cjg67/rescapp.git (push)
upstream	https://github.com/rescatux/rescapp.git (fetch)
upstream	https://github.com/rescatux/rescapp.git (push)

I have followed:

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

I have issued:

git commit --all

I have issued:

git push origin trap

I have issued:

git merge upstream/master

I have issued:

git merge upstream/trap

I have no idea what I need to do to get the changes that it states on the command line to actually show up on my github account.

Regards,

Christopher.

**Comment by cjg67** [comment]
Hello Adrian,

Well I have found that all the changes I made have now appeared on my github account, but they were made to master and not to the trap branch.

I have no idea how to get them onto the correct branch. :(
