### ISSUE TITLE
how to fix boot windows uefi after losing Microsoft Reserved (MSR) partition

### ISSUE THREAD

**Issue by candrapersada** [rescatux/rescapp#65]
When you carelessly delete the system reserved partition, it may cause boot problems, How to fix this problem?

**Comment by adrian15** [comment]
> When you carelessly delete the system reserved partition, it may cause boot problems, How to fix this problem?

Option 1: If it was a simple partition removal you can always use gpart (not gparted) which it's included in Rescatux to undo that partition removal. It's a CLI tool and you are on your own to use it.

Option 2: Use Windows rescue disk.

Option 3: Maybe trying to boot into Windows bypassing that MSR partition but I'm not sure it can be done in UEFI boot mode. Maybe in PC BIOS mode but, I'm not so sure about that one.

**Comment by candrapersada** [comment]
how to create msr new for fix boot Windows?
