### ISSUE TITLE
rescatux shows grub menu then won't boot selection

### ISSUE THREAD

**Issue by Dan-Essin** [rescatux/rescapp#69]
I'm running ubuntu 20.04 on a mac mini. I managed to zap it's grub.
Made a rescatux usb and it boots to its brub menu.
I've tried several entries such as fail-safe. After each selection the machine sounds like it does when it's booting, that is, it momentarily shuts of and the restarts with the selected grub entry.

At this point rescatux, supergrub2 and clonezilla usb's all do nothing.
A ubuntu installer usb proceeds to startup normally as does the linux-boot-repair usb (but it won't repair anything). 

btw - the problem started when I tried to use the ubuntu installer to install on an external HD. When it updated grub as part of the install it whacked both the internal HD and the external HD - then neither would boot.

I really need this to work but I have no idea what to do next.
Please help!

**Comment by adrian15** [comment]
I would reinstall MacOS so that the computer is bootable and then continue from there.

Probably using ReFind would be a good idea too.
