### ISSUE TITLE
Unable to install Rescapp on Debian Bullseye

### ISSUE THREAD

**Issue by PiperKev** [rescatux/rescapp#70]
I was unable to use Rescatux since it's based on Debian Buster and my laptop won't run Buster for some reason.  I am able to load and run the latest Debian, Bullseye (non-free version) but, when I attempt to install rescapp using the commands for "Non-free Rescapp", I get the following dependency errors:

The following packages have unmet dependencies:
 rescapp : Depends: btrfs-tools but it is not installable
                 Depends: lilo but it is not installable

**Comment by adrian15** [comment]
> I was unable to use Rescatux since it's based on Debian Buster and my laptop won't run Buster for some reason. I am able to load and run the latest Debian, Bullseye (non-free version) but, when I attempt to install rescapp using the commands for "Non-free Rescapp", I get the following dependency errors:
> 
> The following packages have unmet dependencies:

> rescapp : Depends: btrfs-tools but it is not installable

This package does not seem to be available in something newer than Buster. Mayb it has been replaced by another package name. The rescapp package would have to be updated to reflect such a change.

> Depends: lilo but it is not installable
Yeah, you probably do not need lilo to use rescapp.

Try to force to install the package even if the dependencies are not met.
I'm not 100% convinced but there should be an apt-get install switch for doing so.

In any case, well, Rescapp has not been tested in Bullseye... so... it might work or not.
