### ISSUE TITLE
applying a patch to rescapp in live environment. 

### ISSUE THREAD

**Issue by RustyRaptor** [rescatux/rescapp#76]
I want to apply a hotfix based on a PR manually inside of the rescatux live CD. Is it as simple as this? 
1. clone the branch that contains the patch
2. Install any missing deps
3. cd into the repo and run `sudo make install`

The main point of my question is will this replace the existing installation with the patched one? 
1. I am assuming the patch is a working one otherwise.

**Comment by adrian15** [comment]
No, it is not. What you have installed in Rescatux cd is a rescapp package.
So you need to release a new deb file and install it manually thanks to `dpkg -i`.

Otherwise you can check where the files are saved and update whatever files you need to update manually.
